<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Activate your Yoda account</h3>
            </div>
            <div class="panel-body">
                <!--<form method="POST" action="?php echo base_url('user/login') ?" class="form-horizontal"> -->
                <form method="POST" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-login-username">Username</label>
                        <div class="col-sm-9">
                            <input name="username" id="f-login-username" class="form-control" type="text" value="<?php echo escape_html($data['username']) ?>" readonly required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-login-password">Password</label>
                        <div class="col-sm-9">
                            <input name="password" id="f-login-password" class="form-control" type="password" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-login-password">Password (confirm)</label>
                        <div class="col-sm-9">
                            <input name="password_again" id="f-login-password" class="form-control" type="password" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <input id="f-login-submit" class="btn btn-primary" type="submit" value="Activate" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
