<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Yoda account activation</h3>
            </div>
            <div class="panel-body">
<?php
if (isset($data['error'])) {
?>
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                    <?php echo escape_html($data['error']); ?>
                </div>
<?php
}
?>
                <form method="POST" class="form-horizontal" validationProcess="YodaPasswordValidation">
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-activation-username">Terms of use</label>
                        <div class="col-sm-9">
Terms of use:
<br>
By accessing and using Yoda, you agree to be bound by the
Yoda terms of use as defined by Utrecht University. These terms are
listed at <a href="https://yoda.uu.nl">https://yoda.uu.nl</a>
                            <br>

                            <div class="checkbox">
                                <label><input type="checkbox" value="" id="cb-activation-tou"><strong>Please accept terms of use</strong></label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-activation-username">Username</label>
                        <div class="col-sm-9">
                            <input name="username" id="f-activation-username" class="form-control" type="text" value="<?php echo escape_html($data['username']) ?>" readonly required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-activation-password">Password</label>
                        <div class="col-sm-9">
                            <input name="password" id="f-activation-password" class="form-control" type="password" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-activation-password-again">Password (confirm)</label>
                        <div class="col-sm-9">
                            <input name="password_again" id="f-activation-password-again" class="form-control" type="password" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <input id="f-activation-submit" class="btn btn-primary" type="submit" value="Activate" />
                        </div>
                    </div>
                </form>

                <div class="alert alert-warning">Please enter a password</div>

                Your password must be in accordance with following requirements:
                <br>
                <br>- It must be between 10 and 32 characters in length
                <br>- It must comply to the following rules:
                <br>&nbsp;&nbsp; - At least 1 capital letter A-Z
                <br>&nbsp;&nbsp; - At least 1 letter a-z
                <br>&nbsp;&nbsp; - At least 1 number 0-9
                <br>&nbsp;&nbsp; - At least 1 special character: !@#=?<>()/\&
            </div>
        </div>
    </div>
</div>
