<?php /* This view is used for any invalid activation hash */ ?>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Yoda account activation</h3>
            </div>
            <div class="panel-body">
                <p>
                    Sorry, your activation link is no longer valid.
                </p>
            </div>
        </div>
    </div>
</div>
