<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Forgot or change password</h3>
            </div>
            <div class="panel-body">
                <?php
                if (isset($data['error'])) {
                    ?>
                    <div class="alert alert-danger">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                        <?php echo escape_html($data['error']); ?>
                    </div>
                    <?php
                }
                ?>
                <form method="POST" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-activation-username">Username</label>
                        <div class="col-sm-9">
                            <input name="username" id="f-forgot-password-username" class="form-control" placeholder="Email address" autofocus="" required="" type="text" />
                            <span id="capitals" class="hidden error text-danger">Username should not contain capital letters.</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <input id="f-forgot-password-submit" class="btn btn-primary" type="submit" value="Send" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
