<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Yoda forgot password</h3>
            </div>
            <div class="panel-body">
                <p>
                    We have sent you an email to reset your password.
                </p>
            </div>
        </div>
    </div>
</div>
