<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Yoda reset password</h3>
            </div>
            <div class="panel-body">
<?php
if (isset($data['error'])) {
?>
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                    <?php echo escape_html($data['error']); ?>
                </div>
<?php
}
?>
                <form method="POST" class="form-horizontal">
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-reset-password-username">Username</label>
                        <div class="col-sm-9">
                            <input name="username" id="f-reset-password-username" class="form-control" type="text" value="<?php echo escape_html($data['username']) ?>" readonly required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-reset-password-password">Password</label>
                        <div class="col-sm-9">
                            <input name="password" id="f-reset-password-password" class="form-control" type="password" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="f-reset-password-password-again">Password (confirm)</label>
                        <div class="col-sm-9">
                            <input name="password_again" id="f-reset-password-password-again" class="form-control" type="password" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <input id="f-activation-submit" class="btn btn-primary" type="submit" value="Reset password" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
