---
name: "Lint and run tests"

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==7.3.0 flake8-import-order==0.19.2 darglint==1.8.1 codespell mypy==1.19.1 types-requests flake8-pyproject==1.2.4
          python -m pip install ./

      - name: Lint with flake8
        run: |
          flake8 --statistics

      - name: Check static typing
        run: |
          mypy yoda_eus --explicit-package-bases

      - name: Check code for common misspellings
        run: |
          codespell -q 3 --skip="*.r,*.xsd,*.json" || true

      - name: Check McCabe complexity
        run: |
          flake8 --max-complexity 10 || true

      - name: Basic flake8 check
        run: |
          flake8 yoda_eus --select=E999,F63,F7,F82,F831

      - name: Install package for tests
        run: |
          pip install wheel
          pip install .[test]

      - name: Run tests
        run: |
          cd yoda_eus
          python3 -m pytest
